version: "3.4"

services:
  api:
    env_file:
      - .env
    image: oven/bun:slim
    volumes:
      - ./api:/app/api
      - ./data:/data
    working_dir: /app/api
    command: >
      sh -c "apt-get update && apt-get install procps -y -qq && bun install && bun run start:dev"
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/London
      - JWT_SECRET=${JWT_SECRET}

  client:
    image: oven/bun:slim
    volumes:
      - ./:/app
    working_dir: /app/client
    environment:
      - VITE_API_URL=/api
    user: "1000:1000"
    command: >
      sh -c "bun install && bun run dev"

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
